### PR TITLE
Update README.md of Contao 4.4

### PR DESCRIPTION
**Pull request by Mynyx**
Consideration of the problem with the reserved keyword ``member``.

### CODE REVIEW

**Comment by fritzmg** [comment]
iirc you need at least doctrine 2.8, which requires PHP 7.1, not 7.2

**Comment by Mynyx** [comment]
I think the fix https://github.com/doctrine/dbal/pull/3674 was merged into Doctrine 2.10?

See also https://github.com/contao/contao/issues/727#issuecomment-549255954 and https://github.com/contao/contao/issues/923#issue-517073544

**Comment by fritzmg** [comment]
Yeah, you are right, I rememberd that wrong :). I think I was referring to `groups`, which happened in earlier versions.

**Comment by fritzmg** [comment]
Added it to the docs too: https://github.com/contao/docs/commit/f11161fae27ce163e76979af717f549fb32e1cd1

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
I guess this is obsolete now that we require PHP 7.2 anyway

**Comment by fritzmg** [comment]
It could still be added to `4.9`.

**Comment by aschempp** [comment]
> It could still be added to `4.9`.

Contao 4.9 requires PHP 7.2 anyway

**Pull request closed without merging**
